stages:
  split:
    cmd: python src/split.py
    deps:
    - data/diamonds.csv
    - src/split.py
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/test.csv
    - data/train.csv
    - src/train.py
    outs:
    - models/model.joblib
    metrics:
    - metrics.json:
        cache: false
